### ISSUE TITLE
Mail Template

### ISSUE THREAD

**Issue by yokimohan123** [payfort/start-php#10]
Hello team Payfort i have my shop which is implemented using payfort api, i need to do the custom email template while purchase a product from my shop, if any possibilities to stop the mail send feature from your server then proceed to send the mail from our server?, or if any alternate source to change the Mail template from your API, is there any feature is available kindly please let me know if any possibilities.

**Comment by alovak** [comment]
Hi! You can turn it of in Dashboard.

Just click on 'Company' menu and turn off notifications:

<img width="782" alt="screen shot 2016-04-21 at 15 23 53" src="https://cloud.githubusercontent.com/assets/19233/14708688/18c6089a-07d5-11e6-9cfe-a618b210eda9.png">

and press 'Update Company Details'
