### ISSUE TITLE
Recurring charges

### ISSUE THREAD

**Issue by crustafari** [payfort/start-php#11]
Hi team!

I have successfully integrated Payfort Start to capture charges following your PHP guide.
https://docs.start.payfort.com/guides/custom-php/

But, I'm wondering how can be managed recurring charges?

Thanks in advance!

**Comment by tukadiya** [comment]
Hello  Team,

i  have to  implement  payment gateway  as  charge  multiple time  same card 
i  am  following  this link  https://docs.start.payfort.com/references/api/#create-a-new-customer
one customer have multiple card and charge any  card  multiple time.

please give  me one example.  i didn't found any documentation for that.
(token can be  used  onces)

Thanks In Advance,
Laxman

**Comment by mslabba** [comment]
Hi Team,

First of all thank you!

Now I am struggling to create a new card for existing customer.
I am using PHP, This is my code 
`
      <?php
	
     require("config.php");
	error_reporting(E_ALL); 
	Start::setApiKey($secretkey);

	$customer_id = $_REQUEST['customer_id'];

	$customer = Start_Customer::get("$customer_id");
		
	try {
		$card = $customer->cards->create(array(
		  "card" => $_REQUEST['token']
		));
	} catch (Start_Error $e) {
	    $error_code = $e->getErrorCode();
	    $error_message = $e->getMessage();
	    // show error
	    echo $error_code.' -'.$error_message;
	}

	if ($card) {
		$response["success"] = 1;
		$response["message"] = "New card has been created.";
		$response['card'] = $card;
	} else {
		$response["success"] = 0;
		$response["message"] = "Failed.";
	}
	echo json_encode($response);
       ?>
`
And I am getting error 
'Fatal error: Uncaught Error: Call to a member function create() on null '

**Comment by abdellatifbakka** [comment]
Hi,
There are a miss of comments in the code, so I can't understand a lot of things from the code like the charge_id var in Capture.php file ...

I hope you can fix that early.

Thanks,
- ABDELLATIF BAKKA.
