### ISSUE TITLE
Amount & Currency have to be passed to createToken method error

### ISSUE THREAD

**Issue by marvz123** [payfort/start-php#14]
Hello,

I have installed the start payment module and successfully tested it using test account. After I switched it to live account and tried to make a purchase, I encountered this (attached) error. Any help please.

Thanks,

Marvin
![unnamed](https://cloud.githubusercontent.com/assets/22780828/19292208/0b56e5e8-904d-11e6-9e8b-913e81d7a879.png)

**Comment by alovak** [comment]
Hi! It's not related to start-php, but to https://docs.start.payfort.com/guides/beautiful.js/

Also it's not related to test or live account.

What I see is that amount and currency was not passed to ```open``` method as it should be:  

```
StartCheckout.open({
  amount:   10000,  // = AED 100.00
  currency: "AED"
});
```

I guess it's because of plugin issues.
