### ISSUE TITLE
How to get payfort secret and open key?

### ISSUE THREAD

**Issue by ssboopathi1991** [payfort/start-php#17]
Now I am using payfort development mode.  I am new from Payfort. How to get the payfort secret key and open key?

EG:
   ```
 $api_keys = array(
        "secret_key" => "test_sec_k_16dc38ad730d6ba806a92",//How to get it
        "open_key"   => "test_open_k_c3f462a1e8277114c1da"//How to get it
    );
```

How to change the title?
![screenshot-sbcheckout payfort com-2017-05-09-13-02-24](https://cloud.githubusercontent.com/assets/7512019/25840304/efa9c4da-34b8-11e7-8c36-ecf9dff8316d.png)

**Comment by alovak** [comment]
Hi!

Here is the link: https://docs.start.payfort.com/guides/api_keys/
