### ISSUE TITLE
You are not allowed to create a charge directly using Card parameters. Please create a token first issue

### ISSUE THREAD

**Issue by salchee** [payfort/start-php#18]
Hi.
Im trying to execute a test transaction, also i'm following every instruction on documentation. But all 'im having is this:
Start_Error_Request Object
(
    [httpStatus:protected] => 400
    [errorCode:protected] => request_invalid
    [message:protected] => You are not allowed to create a charge directly using Card parameters. Please create a token first (see https://docs.start.payfort.com/references/api/#tokens)
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /home1/salchee/public_html/test/src/Start.php
    [line:protected] => 139
...

My code looks like `this:
```
try {
	Start::setApiKey('test_sec_k_01dc012b43b03f073c20d');
  
$result = Start_Charge::create(array(
  "amount" => 1000,
  "currency" => "aed",
  "metadata" => array(
    "reference_id" => "1234567890",
    "tag" => "new"
  ),
  "card" => array(
    "name" => "Abdullah Ahmed",
    "number" => "4242424242424242",
    "exp_month" => 11,
    "exp_year" => 2018,
    "cvc" => "123"
  ),
  "description" => "Two widgets (test@example.com)",
  "email" => "ahmed@example.com"
));
print_r($result);
} catch(Start_Error_Banking $e) {
  // Since it's a decline, Start_Error_Banking will be caught
  print('Status is:' . $e->getHttpStatus() . "\n");
  print('Code is:' . $e->getErrorCode() . "\n");
  print('Message is:' . $e->getMessage() . "\n");

} catch (Start_Error_Request $e) {
  // Invalid parameters were supplied to Start's API
  print_r($e);

} catch (Start_Error_Authentication $e) {
  // There's a problem with that API key you provided
  print_r($e);

} catch (Start_Error $e) {
  // Display a very generic error to the user, and maybe send
  // yourself an email
  print_r($e);

} catch (Exception $e) {
  // Something else happened, completely unrelated to Start
  print_r($e);
  
}
```

**Comment by alovak** [comment]
Hi @salchee!

Please, check this guide https://docs.start.payfort.com/

due to security restrictions card details can't be sent from your server. You have to use our javascrip library for tokenization (https://docs.start.payfort.com/guides/beautiful.js/).
