### ISSUE TITLE
API out of sync with doc

### ISSUE THREAD

**Issue by onlab** [payfort/start-php#7]
From your doc (https://docs.start.payfort.com/references/api/?php#create-a-card) we need to get the customer object to create a card instance but there's no Start_Customer::get() in your class.

**Comment by alovak** [comment]
I'm sorry for this inconvenience. We have to check our api docs...

I think we add this to api docs assuming we can add it to start-php quickly.

**Comment by alovak** [comment]
@onlab it's done now. For charges, refunds and customers.
