### ISSUE TITLE
where is Start_Refund class?

### ISSUE THREAD

**Issue by Telrik** [payfort/start-php#9]
class Start_Refund {

    public static function create(array $data) {
        $return_data = Start_Request::make_request("refund", $data);
        return $return_data;
    }

}

**Comment by alovak** [comment]
Hi! There is no Refund class in library yet.

It's easy to add such (with tests). Don't you mind to add it to the repo (as PR?).

**Comment by Telrik** [comment]
well where is problem with url it's not /refunds/ its charges/id/refund or something.
so i also put some ugly code in stream.php

**Comment by alovak** [comment]
Btw, there is a bug in Request.php. I can't fix it now... but fallback works not as it should be... If stream fails then curl (as far as I know) will not work.

**Comment by alovak** [comment]
@Telrik here it is

https://github.com/payfort/start-php/pull/12
